version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "TPM-2526"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1w4aey6a6umtv"
s3_prefix = "TPM-2526"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
